accounts/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('register', views.UserRegisterView.as_view() , name='register'),
    path('login', views.UserLoginView.as_view(), name='login'),
    path('profile', views.profile, name='profile'),
    path('profile', views.logout, name='logout'),
]

book/urls.py
from django.urls import path   

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:book_id>', views.details, name='details'),
    path('deposit', views.deposit, name='deposit'),
    path('borrow', views.borrow, name='borrow'),
    path('return', views.return_book, name='return'),
]

library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("book.urls")),
    path('accounts/', include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserVault(models.Model):
    user = models.OneToOneField(User, related_name="vault", on_delete=models.CASCADE)
    balance = models.IntegerField()

borrowings/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book

from .constants import BORROW, RETURN, TRANSACTION_TYPE
from datetime import timezone
import datetime

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    mode = models.IntegerField(choices=TRANSACTION_TYPE)
    balance_after_transaction = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from typing import Any
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import UserVault

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def save(self, commit=True):
        user = super().save(commit = False)
        if commit == True:
            user.save()
            vault = UserVault.objects.create(
                user = user,
                balance = 0,
            )
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView
from .forms import UserRegistrationForm

from borrowings.models import Transaction

class UserRegisterView(SuccessMessageMixin, CreateView):
    template_name = "accounts/signup.html"
    form_class = UserRegistrationForm
    success_message = "User account created successfully"
    success_url = reverse_lazy("index")

class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = "accounts/login.html"
    success_message = "Successfully Logged In"
    success_url = reverse_lazy("index")

@login_required
def profile(request):
    transactions = Transaction.objects.filter(user=request.user)
    return render(request, "accounts/profile.html", {
        "transactions": transactions,
    })

@login_required
def logout(request):
    logout(request)
    return redirect(reverse_lazy("index"))

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<form class="max-w-md mx-auto [&_input]:bg-gray-50 [&_input]:border [&_input]:border-gray-300 [&_input]:text-gray-900 [&_input]:text-sm [&_input]:rounded-lg 
[&_input]:focus:ring-blue-500 [&_input]:focus:border-blue-500 [&_input]:block [&_input]:w-full [&_input]:p-2.5 [&_input]:dark:bg-gray-700 [&_input]:dark:border-gray-600 [&_input]:dark:placeholder-gray-400 
[&_input]:dark:text-white [&_input]:dark:focus:ring-blue-500 [&_input]:dark:focus:border-blue-500" method="POST">
        <h2 class="text-center text-2xl font-bold">Log In</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="mt-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="submit">Log In</button>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="max-w-2xl mx-auto">
        <h2 class="text-2xl font-bold mb-3">Profile</h2>
        <div>  
            <span><b>Name:</b> {{ user.first_name }} {{ user.last_name }}</span><br/>
            <span><b>Email:</b> {{ user.email }}</span><br/>
        </div>
        <h2 class="text-2xl font-bold mb-3">Transactions</h2>
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">ID</th>
                    <th scope="col" class="px-6 py-3">Name</th>
                    <th scope="col" class="px-6 py-3">Borrowing Price</th>
                    <th scope="col" class="px-6 py-3">Balance After Transaction</th>
                    <th scope="col" class="px-6 py-3">Transaction Type</th>
                    <th scope="col" class="px-6 py-3">Date & Time of Transaction</th>
                    <th scope="col" class="px-6 py-3">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{ transaction.id }}</td>
                        <td class="px-6 py-4">{{ transaction.book.title }}</td>
                        <td class="px-6 py-4">{{ transaction.book.borrowing_price }}$</td>
                        <td class="px-6 py-4">{{ transaction.balance_after_transaction }}</td>
                        <td class="px-6 py-4">{{ transaction.get_mode_display }}</td>
                        <td class="px-6 py-4">{{ transaction.timestamp }}</td>
                        <td>
                            {% if transaction.mode == 0 %}
                                <form action="{% url 'return' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" id="book_id" name="book_id" value="{{ transaction.book.id }}" />
                                    <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="submit">Return</button>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<form class="max-w-md mx-auto [&_input]:bg-gray-50 [&_input]:border [&_input]:border-gray-300 [&_input]:text-gray-900 [&_input]:text-sm [&_input]:rounded-lg 
[&_input]:focus:ring-blue-500 [&_input]:focus:border-blue-500 [&_input]:block [&_input]:w-full [&_input]:p-2.5 [&_input]:dark:bg-gray-700 [&_input]:dark:border-gray-600 [&_input]:dark:placeholder-gray-400 
[&_input]:dark:text-white [&_input]:dark:focus:ring-blue-500 [&_input]:dark:focus:border-blue-500" method="POST">
        <h2 class="text-2xl font-bold text-center">Sign Up</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="mt-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="submit">Sign Up</button>
    </form>
{% endblock %}