book/urls.py
from django.urls import path   

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:book_id>', views.details, name='details'),
    path('deposit', views.deposit, name='deposit'),
    path('borrow', views.borrow, name='borrow'),
    path('return', views.return_book, name='return'),
]

library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("book.urls")),
    path('accounts/', include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.contrib.auth.models import User
from .constants import GENRE_CHOICES, REVIEW_CHOICES

class Book(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    image = models.ImageField(upload_to="media/books/")
    borrowing_price = models.IntegerField()
    category = models.CharField(max_length=100, choices=GENRE_CHOICES)

    def __str__(self):
        return self.title

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=REVIEW_CHOICES)
    review = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('book', 'user',)

book/forms.py
from typing import Any
from django import forms 
from django.contrib.auth.models import User

from .models import Review
from borrowings.models import Transaction

class DepositForm(forms.Form):
    amount = forms.IntegerField()

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount <= 0:
            raise forms.ValidationError("Amount must be non-negative")
        return amount
    
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rating', 'review',)

    def __init__(self, *args, **kwargs):
        self.book = kwargs.pop('book')
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.book = self.book
        self.instance.user = self.user
        print(dir(self.instance))
        return super().save()
    
    def clean(self):
        transaction_count = Transaction.objects.filter(book=self.book, user=self.user).count()
        if transaction_count == 0:
            raise forms.ValidationError("You must borrow this book to review on it")

        try:
            existing_review = Review.objects.get(book=self.book, user=self.user)
        except Review.DoesNotExist:
            existing_review = None
        if existing_review:
            raise forms.ValidationError("You cannot review more than one time.")

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
from django.db.models import F
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings

from .models import Book, Review
from .constants import GENRE_CHOICES
from borrowings.constants import TRANSACTION_TYPE, BORROW, RETURN
from .forms import DepositForm, ReviewForm
from borrowings.models import Transaction

def index(request):
    if 'genre' in request.GET:
        genre = request.GET['genre']
        books = Book.objects.filter(category=genre)
    else:
        books = Book.objects.all()
    genres = GENRE_CHOICES
    return render(request, "book/index.html", {
        "book_list": books,
        "genres": genres,
    })

def details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    reviews = Review.objects.filter(book=book).order_by("-timestamp")

    if request.method == "POST":
        if request.user.is_authenticated == False:
            return HttpResponse("You are not authorized for this action.")
        review_form = ReviewForm(request.POST, book=book, user=request.user)
        if review_form.is_valid():
            review_form.save()
            messages.success(request, message="Review posted successfully")
    else:
        review_form = ReviewForm(user=request.user, book=book)

    can_borrow = False
    why = ""

    if request.user.is_authenticated:
        try:
            borrow_count = Transaction.objects.filter(book=book, user=request.user, mode=BORROW).count()
            return_count = Transaction.objects.filter(book=book, user=request.user, mode=RETURN).count()
            if borrow_count > return_count:
                transaction = True
            else:
                transaction = None
        except Transaction.DoesNotExist:
            transaction = None
        
        if transaction is not None:
            why = "you already have borrowed a copy of this book and haven't returned yet"
        elif request.user.vault.balance < book.borrowing_price:
            why = "you don't have enough balance to borrow this book. Please deposit some money first"
        else:
            can_borrow = True

    return render(request, "book/details.html", {
        "book": book,
        "can_borrow": can_borrow,
        "why": why,
        "review_form": review_form,
        "reviews": reviews,
    })

@login_required
def deposit(request):
    if request.method == "POST":
        form = DepositForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            vault = request.user.vault
            vault.balance = F("balance") + amount
            vault.save()
            mail_text = render_to_string("email/deposit.html", {
                "amount": amount,
                "user": request.user,
            })
            send_mail("Deposit Info - Library Management System", "", settings.EMAIL_HOST_USER, [request.user.email], 
                      html_message=mail_text)
            messages.success(request, message=f"Successfully Deposited {amount}")
            return redirect("index")
    else:
        form = DepositForm()
    return render(request, "book/deposit.html", {
        "form": form
    })

@login_required
def borrow(request):
    if request.method == "POST":
        book_id = int(request.POST['book_id'])
        book = get_object_or_404(Book, pk=book_id)
        can_borrow = False
        why = ""

        try:
            borrow_count = Transaction.objects.filter(book=book, user=request.user, mode=BORROW).count()
            return_count = Transaction.objects.filter(book=book, user=request.user, mode=RETURN).count()
            if borrow_count > return_count:
                transaction = True
            else:
                transaction = None
        except:
            transaction = None
        
        if transaction is not None:
            why = "you already have borrowed a copy of this book and haven't returned yet"
        elif request.user.vault.balance < book.borrowing_price:
            why = "you don't have enough balance to borrow this book. Please deposit some money first"
        else:
            can_borrow = True

        if not can_borrow:
            return HttpResponse(why)
        
        vault = request.user.vault
        vault.balance = vault.balance - book.borrowing_price
        vault.save()

        print(dir(vault))

        trx = Transaction.objects.create(
            user = request.user,
            book = book,
            mode = BORROW,
            balance_after_transaction = vault.balance,
        )

        mail_text = render_to_string("email/borrow.html", {
            "transaction": trx,
            "user": request.user,
        })
        send_mail("Borrow Info - Library Management System", "", settings.EMAIL_HOST_USER, [request.user.email], 
                    html_message=mail_text)

        messages.success(request, message="Successfully borrowed the book")
        return redirect(reverse("details", args=(book_id,)))
    
@login_required
def return_book(request):
    if request.method == "POST":
        book_id = request.POST["book_id"]
        try:
            last_transaction = Transaction.objects.filter(user=request.user, book__id=book_id).latest('timestamp')
        except Transaction.DoesNotExist:
            return HttpResponse("You cannot return a book that you didn't borrow (or borrowed and returned before)")
        if last_transaction.mode == RETURN:
            return HttpResponse("You cannot return a book that you didn't borrow (or borrowed and returned before)")
        book = get_object_or_404(Book, pk=book_id)
        vault = request.user.vault
        vault.balance += book.borrowing_price
        vault.save()

        Transaction.objects.create(
            user = request.user,
            book = book,
            mode = RETURN,
            balance_after_transaction = vault.balance,
        )

        messages.success(request, message=f"Successfully returned the book {book}")
        return redirect("profile")

book/templates/book/deposit.html
{% extends 'base.html' %}

{% block content %}
    <form class="max-w-md mx-auto" method="POST">
        <h2 class="text-2xl font-bold">Deposit Money</h2>
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="font-bold text-red-700">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="mb-5">
            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="review">Amount</label>
            <input class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" name="amount" required />
        </div>
        <button class="mt-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="submit">Review</button>
    </form>
{% endblock %}

book/templates/book/details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mx-auto">
        <div class="flex m-4">
            <img width="300px" src={{ book.image.url }} />
            <div class="p-4">
                <h2 class="text-3xl font-bold mb-3">{{ book.title }}</h2>
                <p class="text-lg mb-16">{{ book.description }}</p>
                <span>Borrowing Price: <b>{{ book.borrowing_price }}$</b></span><br/>
                <span>Category: <b>{{ book.get_category_display }}</b></span>

                {% if user.is_authenticated %}
                    {% if can_borrow %}
                        <form method="POST" action="{% url 'borrow' %}">
                            {% csrf_token %}
                            <input type="hidden" id="book_id" name="book_id" value="{{ book.id }}" /><br/>
                            <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="submit">Borrow</button>
                        </form>
                    {% else %}
                        <p><b>You cannot borrow this book because {{ why }}</b></p>
                    {% endif %}
                {% else %}
                    <p>You must login or create an account to borrow this book</p>
                {% endif %}
            </div>
        </div>

        

        <h2 class="text-2xl font-bold">Reviews</h2>
        {% for review in reviews %}
        <article>
            <div class="flex items-center mb-4">
                <!-- <img class="w-10 h-10 me-4 rounded-full" src="/docs/images/people/profile-picture-5.jpg" alt=""> -->
                <div class="font-medium dark:text-white">
                    <p>{{ review.user.first_name }} {{ review.user.last_name }} <time datetime="2014-08-16 19:00" class="block text-sm text-gray-500 dark:text-gray-400">Joined {{ user.date_joined | timesince }} ago</time></p>
                </div>
            </div>
            <div class="flex items-center mb-1 space-x-1 rtl:space-x-reverse">
                {{ review.get_rating_display }}
                <h3 class="ms-2 text-sm font-semibold text-gray-900 dark:text-white">{{ review.rating }}.0/5.0</h3>
            </div>
            <footer class="mb-5 text-sm text-gray-500 dark:text-gray-400"><p>Reviewed <time datetime="2017-03-03 19:00">{{ review.timestamp | timesince }}</time> ago</p></footer>
            <p class="mb-2 text-gray-500 dark:text-gray-400">{{ review.review }}</p>
        </article>
        {% endfor %}
        {% if user.is_authenticated %}
            <form class="max-w-md mx-auto" method="POST">
                Leave a Review
                {% if review_form.non_field_errors %}
                    <div class="font-bold text-red-700">
                        {{ review_form.non_field_errors }}
                    </div>
                {% endif %}
                {% csrf_token %}
                <div class="mb-5">
                    <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="review">Review</label>
                    <textarea class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" name="review" required></textarea>
                </div>
                <label for="rating">
                <div class="rating">
                    <input type="radio" name="rating" class="mask mask-star-2 bg-orange-400" value="1" checked />
                    <input type="radio" name="rating" class="mask mask-star-2 bg-orange-400" value="2" />
                    <input type="radio" name="rating" class="mask mask-star-2 bg-orange-400" value="3" />
                    <input type="radio" name="rating" class="mask mask-star-2 bg-orange-400" value="4" />
                    <input type="radio" name="rating" class="mask mask-star-2 bg-orange-400" value="5" />
                </div><br/>
                <button class="mt-2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="submit">Review</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

book/templates/book/index.html
{% extends "base.html" %}

{% block content %}
    <div class="flex">
        <div id="category-sidebar">
            <h2 class="text-xl font-bold p-4">Categories</h2>
            <div class="w-48 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                {% for genre in genres %}
                    <a href="?genre={{ genre.0 }}" class="block w-full px-4 py-2 border-b border-gray-200 cursor-pointer hover:bg-gray-100 hover:text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:border-gray-600 dark:hover:bg-gray-600 dark:hover:text-white dark:focus:ring-gray-500 dark:focus:text-white">
                        {{ genre.1 }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="p-4">
            <h1 class="text-2xl font-bold p-4">Books</h1>
            <div class="flex flex-wrap gap-2">
                {% for book in book_list %}
                <div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                    <a href="{% url 'details' book.id %}">
                        <img class="p-8 rounded-t-lg w-96 h-[500px] object-cover" src="{{ book.image.url }}" alt="product image" />
                    </a>
                    <div class="px-5 pb-5">
                        <a href="{% url 'details' book.id %}">
                            <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{ book.title }}</h5>
                        </a>
                        <div class="flex items-center mt-2.5 mb-5">
                            <div class="flex items-center space-x-1 rtl:space-x-reverse">
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                                <svg class="w-4 h-4 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                </svg>
                            </div>
                            <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-3">5.0</span>
                        </div>
                        <p class="line-clamp-3 mb-3">{{ book.description }}</p>
                        <div class="flex items-center justify-between">
                            <span class="text-3xl font-bold text-gray-900 dark:text-white">${{ book.borrowing_price }}</span>
                            <a href="{% url 'details' book.id %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">See Details</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}